[package]
name = "moka"
version = "0.1.0-alpha.1"
authors = ["Tatsuya Kawano <tatsuya@hibaridb.org>"]
edition = "2018"

description = "A fast and concurrent cache library inspired by Caffeine (Java) and Ristretto (Go)"
license = "MIT OR Apache-2.0"
# homepage = "https://"
documentation = "https://docs.rs/moka/"
repository = "https://github.com/moka-rs/moka"
keywords = ["concurrent", "cache"]
categories = ["concurrency", "caching"]
readme = "README.md"
exclude = [".devcontainer", ".github", ".vscode"]

[dependencies]
cht = "0.4"
crossbeam-channel = "0.4"
# hierarchical_hash_wheel_timer = "1.0"
lazy_static = "1.4"
num_cpus = "1.13"
parking_lot = "0.10"
scheduled-thread-pool = "0.2"

[dev-dependencies]
getrandom = "0.2"
