[package]
name = "moka"
version = "0.1.0-beta.1"
authors = ["Tatsuya Kawano <tatsuya@hibaridb.org>"]
edition = "2018"

description = "A fast and concurrent cache library inspired by Caffeine (Java) and Ristretto (Go)"
license = "MIT OR Apache-2.0"
# homepage = "https://"
documentation = "https://docs.rs/moka/"
repository = "https://github.com/moka-rs/moka"
keywords = ["concurrent", "cache"]
categories = ["concurrency", "caching"]
readme = "README.md"
exclude = [".devcontainer", ".github", ".vscode"]

[dependencies]
cht = "0.4"
crossbeam-channel = "0.5"
# hierarchical_hash_wheel_timer = "1.0"
num_cpus = "1.13"
once_cell = "1.5"
parking_lot = "0.11"
# v0.7.1 or newer should be used as v0.7.0 will not compile on non-x86_64 platforms.
# https://github.com/metrics-rs/quanta/pull/38
quanta = "0.7.1"
scheduled-thread-pool = "0.2"

[dev-dependencies]
getrandom = "0.2"
