[package]
name = "moka"
version = "0.2.0"
authors = ["Tatsuya Kawano <tatsuya@hibaridb.org>"]
edition = "2018"

description = "A fast and concurrent cache library inspired by Caffeine (Java) and Ristretto (Go)"
license = "MIT OR Apache-2.0"
# homepage = "https://"
documentation = "https://docs.rs/moka/"
repository = "https://github.com/moka-rs/moka"
keywords = ["concurrent", "cache"]
categories = ["concurrency", "caching"]
readme = "README.md"
exclude = [".devcontainer", ".github", ".vscode"]
build = "build.rs"

# https://docs.rs/about/metadata
[package.metadata.docs.rs]
features = ["runtime-tokio"]

[features]
default = []
runtime-actix = ["actix-rt", "tokio"]
runtime-async-std = ["async-std"]
runtime-tokio = ["tokio"]

[dependencies]
cht = "0.4"
crossbeam-channel = "0.5"
num_cpus = "1.13"
once_cell = "1.5"
parking_lot = "0.11"
# v0.7.1 or newer should be used as v0.7.0 will not compile on non-x86_64 platforms.
# https://github.com/metrics-rs/quanta/pull/38
quanta = "0.7.1"
scheduled-thread-pool = "0.2"

# Optional async runtimes
actix-rt = { version = "2.0", default-features = false, optional = true }
async-std = { version = "1.9", features = ["attributes"], optional = true }
tokio = { version = "1.2", features = ["rt-multi-thread", "time", "macros"], optional = true }

[dev-dependencies]
futures = "0.3"
getrandom = "0.2"
skeptic = "0.13"
tokio = { version = "1.1", features = ["rt-multi-thread", "macros" ] }

[build-dependencies]
skeptic = "0.13"
