version: 2
jobs:
  rust/coverage:
    machine: true
    steps:
      - checkout
      - run:
          name: Coverage with docker
          command: docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin cargo tarpaulin -v --ciserver circle-ci --coveralls ${COVERALLS_TOKEN} --timeout 600

workflows:
  build:
    jobs:
    - rust/coverage
  version: 2
