version: 2
jobs:
  rust/coverage:
    machine: true
    steps:
      - checkout
      - run:
          name: Run cargo tarpaulin (Allowing a failure)
          command: |
            docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin \
              RUSTFLAGS='--cfg circleci' \
                cargo tarpaulin -v \
                  --features 'future, dash' \
                  --ciserver circle-ci \
                  --coveralls ${COVERALLS_TOKEN} \
                  --timeout 600 \
            || true

workflows:
  build:
    jobs:
    - rust/coverage
  version: 2
