name: CI

on:
  push:
    paths-ignore:
    - '.devcontainer/**'
    - '.gitpod.yml'
    - '.vscode/**'
  pull_request:
    paths-ignore:
    - '.devcontainer/**'
    - '.gitpod.yml'
    - '.vscode/**'
  schedule:
    # Run against the last commit on the default branch on Friday at 8pm (UTC?)
    - cron:  '0 20 * * 5'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          # - 1.46.0  # MSRV (future)
          # - 1.45.2  # MSRV (no features)
          - 1.49.0  # Temporary MSRV

    steps:
      - name: Checkout Moka
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - name: cargo clean
        uses: actions-rs/cargo@v1
        with:
          command: clean

      - name: Build (no features)
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Run tests (no features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
        env:
          RUSTFLAGS: '--cfg skeptic'

      - name: Run tests (future)
        uses: actions-rs/cargo@v1
        if: ${{ matrix.rust != '1.45.2' }}
        with:
          command: test
          args: --features future

      - name: Run tests (release, no features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Run tests (release, future)
        uses: actions-rs/cargo@v1
        if: ${{ matrix.rust != '1.45.2' }}
        with:
          command: test
          args: --release --features future
        env:
          RUSTFLAGS: '--cfg skeptic'

      - name: Run tests (future, without atomic64)
        uses: actions-rs/cargo@v1
        if: ${{ matrix.rust != '1.45.2' }}
        with:
          command: test
          args: --release --no-default-features --features future
        env:
          RUSTFLAGS: '--cfg skeptic'

      - name: Run UI tests (future, trybuild)
        uses: actions-rs/cargo@v1
        if: ${{ matrix.rust == 'stable' }}
        with:
          command: test
          args: ui_trybuild --release --features future
        env:
          RUSTFLAGS: '--cfg trybuild'

      - name: Run Rustfmt
        uses: actions-rs/cargo@v1
        if: ${{ matrix.rust == 'stable' }}
        with:
          command: fmt
          args: --all -- --check

      - name: Run Clippy
        uses: actions-rs/clippy-check@v1
        if: ${{ matrix.rust == 'stable' || matrix.rust == 'beta' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features future -- -D warnings
